In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([1, 2, 3, 4])
type(x), x.shape

(numpy.ndarray, (4,))

In [3]:
x.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [4]:
X = x.reshape(1, 4)

In [5]:
float(np.dot(np.array([1, 2, 3, 4]), np.array([3, 4, 5, 6])))

50.0

In [6]:
data = {'a': [1, 2, 3, 4]}
df = pd.DataFrame(data)
df

a
0  1
1  2
2  3
3  4

In [7]:
df.shape, type(df)

((4, 1), pandas.core.frame.DataFrame)

In [8]:
np.dot(x, df)

array([30])

In [9]:
np.array([[1, 2, 3, 4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [11]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = x.reshape(2, 2)
np.dot(x, y)

array([[ 7, 10],
       [15, 22]])

In [12]:
x, y

(array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [3, 4]]))